// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHwLI2UYg_D6WfB1-k_3rFICO77dSvGio',
    appId: '1:974682768262:android:862b6c4416de5c4d966207',
    messagingSenderId: '974682768262',
    projectId: 'dailyspace',
    storageBucket: 'dailyspace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdwT0nO1Fv0f_3CtC9yCo9W2GBuLcQVJE',
    appId: '1:974682768262:ios:cf29323afd18f7e8966207',
    messagingSenderId: '974682768262',
    projectId: 'dailyspace',
    storageBucket: 'dailyspace.appspot.com',
    androidClientId: '974682768262-2r99sk8n7go6udk9hb417523j3obid5g.apps.googleusercontent.com',
    iosClientId: '974682768262-248a95l0f0t68m1eq7gfe5se8gm9m5ea.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADgvndj0_qt7lgvtmcHR_VweU6zPodv94',
    appId: '1:974682768262:web:24cd8e15863a56b6966207',
    messagingSenderId: '974682768262',
    projectId: 'dailyspace',
    authDomain: 'dailyspace.firebaseapp.com',
    storageBucket: 'dailyspace.appspot.com',
    measurementId: 'G-00849P2ZNH',
  );

}